// Code generated by protoc-gen-go.
// source: proto.proto
// DO NOT EDIT!

/*
Package api is a generated protocol buffer package.

整体协议 分成  API、RET、公用结构体、相应api协议（结构体、协议）

It is generated from these files:
	proto.proto

It has these top-level messages:
	BaseHeartReq
	BaseHeartResp
	LogInfo
	LogInfoReq
	LogInfoResp
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type API int32

const (
	// 基础,心跳
	API_base_heart API = 0
	API_add_log    API = 1
)

var API_name = map[int32]string{
	0: "base_heart",
	1: "add_log",
}
var API_value = map[string]int32{
	"base_heart": 0,
	"add_log":    1,
}

func (x API) String() string {
	return proto.EnumName(API_name, int32(x))
}
func (API) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// 返回结果
type RET int32

const (
	RET_RET_OK  RET = 0
	RET_RET_ERR RET = 1
)

var RET_name = map[int32]string{
	0: "RET_OK",
	1: "RET_ERR",
}
var RET_value = map[string]int32{
	"RET_OK":  0,
	"RET_ERR": 1,
}

func (x RET) String() string {
	return proto.EnumName(RET_name, int32(x))
}
func (RET) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// 日志等级
type LOG_LEAVE int32

const (
	LOG_LEAVE_LEAVE_TRACK LOG_LEAVE = 0
	LOG_LEAVE_LEAVE_DEBUG LOG_LEAVE = 1
	LOG_LEAVE_LEAVE_INFO  LOG_LEAVE = 2
	LOG_LEAVE_LEAVE_WARR  LOG_LEAVE = 3
	LOG_LEAVE_LEAVE_ERROR LOG_LEAVE = 4
)

var LOG_LEAVE_name = map[int32]string{
	0: "LEAVE_TRACK",
	1: "LEAVE_DEBUG",
	2: "LEAVE_INFO",
	3: "LEAVE_WARR",
	4: "LEAVE_ERROR",
}
var LOG_LEAVE_value = map[string]int32{
	"LEAVE_TRACK": 0,
	"LEAVE_DEBUG": 1,
	"LEAVE_INFO":  2,
	"LEAVE_WARR":  3,
	"LEAVE_ERROR": 4,
}

func (x LOG_LEAVE) String() string {
	return proto.EnumName(LOG_LEAVE_name, int32(x))
}
func (LOG_LEAVE) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

// ============================ base_heart 心跳 =============================
type BaseHeartReq struct {
	Seq int32 `protobuf:"varint,1,opt,name=seq" json:"seq,omitempty"`
}

func (m *BaseHeartReq) Reset()                    { *m = BaseHeartReq{} }
func (m *BaseHeartReq) String() string            { return proto.CompactTextString(m) }
func (*BaseHeartReq) ProtoMessage()               {}
func (*BaseHeartReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *BaseHeartReq) GetSeq() int32 {
	if m != nil {
		return m.Seq
	}
	return 0
}

type BaseHeartResp struct {
	Seq int32 `protobuf:"varint,1,opt,name=seq" json:"seq,omitempty"`
}

func (m *BaseHeartResp) Reset()                    { *m = BaseHeartResp{} }
func (m *BaseHeartResp) String() string            { return proto.CompactTextString(m) }
func (*BaseHeartResp) ProtoMessage()               {}
func (*BaseHeartResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *BaseHeartResp) GetSeq() int32 {
	if m != nil {
		return m.Seq
	}
	return 0
}

// ============================ add_log 增加log =============================
type LogInfo struct {
	UserId    int64     `protobuf:"varint,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	LogLeave  LOG_LEAVE `protobuf:"varint,2,opt,name=log_leave,json=logLeave,enum=api.LOG_LEAVE" json:"log_leave,omitempty"`
	Timestamp int64     `protobuf:"varint,3,opt,name=timestamp" json:"timestamp,omitempty"`
	FileName  string    `protobuf:"bytes,4,opt,name=file_name,json=fileName" json:"file_name,omitempty"`
	FuncName  string    `protobuf:"bytes,5,opt,name=func_name,json=funcName" json:"func_name,omitempty"`
	FileNo    int32     `protobuf:"varint,6,opt,name=file_no,json=fileNo" json:"file_no,omitempty"`
	LogInfo   string    `protobuf:"bytes,7,opt,name=log_info,json=logInfo" json:"log_info,omitempty"`
}

func (m *LogInfo) Reset()                    { *m = LogInfo{} }
func (m *LogInfo) String() string            { return proto.CompactTextString(m) }
func (*LogInfo) ProtoMessage()               {}
func (*LogInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *LogInfo) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *LogInfo) GetLogLeave() LOG_LEAVE {
	if m != nil {
		return m.LogLeave
	}
	return LOG_LEAVE_LEAVE_TRACK
}

func (m *LogInfo) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *LogInfo) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *LogInfo) GetFuncName() string {
	if m != nil {
		return m.FuncName
	}
	return ""
}

func (m *LogInfo) GetFileNo() int32 {
	if m != nil {
		return m.FileNo
	}
	return 0
}

func (m *LogInfo) GetLogInfo() string {
	if m != nil {
		return m.LogInfo
	}
	return ""
}

type LogInfoReq struct {
	LogDataList []*LogInfo `protobuf:"bytes,1,rep,name=log_data_list,json=logDataList" json:"log_data_list,omitempty"`
}

func (m *LogInfoReq) Reset()                    { *m = LogInfoReq{} }
func (m *LogInfoReq) String() string            { return proto.CompactTextString(m) }
func (*LogInfoReq) ProtoMessage()               {}
func (*LogInfoReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *LogInfoReq) GetLogDataList() []*LogInfo {
	if m != nil {
		return m.LogDataList
	}
	return nil
}

type LogInfoResp struct {
	Ret RET `protobuf:"varint,1,opt,name=ret,enum=api.RET" json:"ret,omitempty"`
}

func (m *LogInfoResp) Reset()                    { *m = LogInfoResp{} }
func (m *LogInfoResp) String() string            { return proto.CompactTextString(m) }
func (*LogInfoResp) ProtoMessage()               {}
func (*LogInfoResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *LogInfoResp) GetRet() RET {
	if m != nil {
		return m.Ret
	}
	return RET_RET_OK
}

func init() {
	proto.RegisterType((*BaseHeartReq)(nil), "api.base_heart_req")
	proto.RegisterType((*BaseHeartResp)(nil), "api.base_heart_resp")
	proto.RegisterType((*LogInfo)(nil), "api.log_info")
	proto.RegisterType((*LogInfoReq)(nil), "api.log_info_req")
	proto.RegisterType((*LogInfoResp)(nil), "api.log_info_resp")
	proto.RegisterEnum("api.API", API_name, API_value)
	proto.RegisterEnum("api.RET", RET_name, RET_value)
	proto.RegisterEnum("api.LOG_LEAVE", LOG_LEAVE_name, LOG_LEAVE_value)
}

func init() { proto.RegisterFile("proto.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 399 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0x6f, 0x6b, 0xdb, 0x30,
	0x10, 0xc6, 0xa7, 0xaa, 0xb5, 0xe3, 0xf3, 0xea, 0x1a, 0xbd, 0xa9, 0xf7, 0x87, 0x11, 0xbc, 0x37,
	0x21, 0x85, 0xc0, 0xb2, 0x4f, 0xe0, 0xad, 0x5e, 0x09, 0x0b, 0xcd, 0x38, 0xb2, 0xed, 0xdd, 0x84,
	0x5a, 0x2b, 0x99, 0xc0, 0xb6, 0x5c, 0x4b, 0xd9, 0xa7, 0xdd, 0x87, 0x19, 0x92, 0xdb, 0x98, 0x41,
	0xdf, 0x98, 0xbb, 0xe7, 0xf7, 0x3c, 0x67, 0xee, 0x10, 0xc4, 0x5d, 0xaf, 0xad, 0x5e, 0xf8, 0x2f,
	0xa3, 0xa2, 0x53, 0x79, 0x0e, 0xc9, 0x9d, 0x30, 0x92, 0xff, 0x96, 0xa2, 0xb7, 0xbc, 0x97, 0x0f,
	0x2c, 0x05, 0x6a, 0xe4, 0x43, 0x46, 0xa6, 0x64, 0x76, 0x86, 0xae, 0xcc, 0xdf, 0xc3, 0xc5, 0x7f,
	0x1e, 0xd3, 0x3d, 0x63, 0xfa, 0x4b, 0x60, 0x52, 0xeb, 0x3d, 0x57, 0xed, 0x4e, 0xb3, 0x4b, 0x08,
	0x0f, 0x46, 0xf6, 0x5c, 0x55, 0xde, 0x42, 0x31, 0x70, 0xed, 0xaa, 0x62, 0x57, 0x10, 0x39, 0x53,
	0x2d, 0xc5, 0x1f, 0x99, 0x9d, 0x4c, 0xc9, 0x2c, 0x59, 0x26, 0x0b, 0xd1, 0xa9, 0xc5, 0x7a, 0x73,
	0xc3, 0xd7, 0x65, 0xf1, 0xa3, 0x44, 0x37, 0x65, 0xed, 0x38, 0x7b, 0x0b, 0x91, 0x55, 0x8d, 0x34,
	0x56, 0x34, 0x5d, 0x46, 0xfd, 0x9c, 0x51, 0x60, 0x6f, 0x20, 0xda, 0xa9, 0x5a, 0xf2, 0x56, 0x34,
	0x32, 0x3b, 0x9d, 0x92, 0x59, 0x84, 0x13, 0x27, 0xdc, 0x8a, 0x46, 0x7a, 0x78, 0x68, 0xef, 0x07,
	0x78, 0xf6, 0x08, 0x0f, 0xed, 0xbd, 0x87, 0x97, 0x10, 0x0e, 0x49, 0x9d, 0x05, 0x7e, 0x81, 0xc0,
	0xe7, 0x34, 0x7b, 0x35, 0xae, 0x90, 0x85, 0x3e, 0x14, 0xd6, 0x7a, 0xbf, 0x6a, 0x77, 0x3a, 0x2f,
	0xe0, 0xe5, 0x13, 0xf2, 0x57, 0xfa, 0x00, 0xe7, 0xae, 0xaf, 0x84, 0x15, 0xbc, 0x56, 0xc6, 0x66,
	0x64, 0x4a, 0x67, 0xf1, 0xf2, 0xdc, 0x2f, 0xf3, 0xe4, 0xc4, 0xb8, 0xd6, 0xfb, 0x6b, 0x61, 0xc5,
	0x5a, 0x19, 0x9b, 0x5f, 0x0d, 0x91, 0xc7, 0x11, 0xa6, 0x63, 0xaf, 0x81, 0xf6, 0xd2, 0xfa, 0x0b,
	0x25, 0xcb, 0x89, 0x4f, 0x62, 0xb9, 0x45, 0x27, 0xce, 0x73, 0xa0, 0xc5, 0xb7, 0x15, 0x4b, 0x00,
	0xc6, 0xd3, 0xa7, 0x2f, 0x58, 0x0c, 0xa1, 0xa8, 0x2a, 0x5e, 0xeb, 0x7d, 0x4a, 0xe6, 0xef, 0x80,
	0x62, 0xb9, 0x65, 0x00, 0x01, 0x96, 0x5b, 0xbe, 0xf9, 0x3a, 0x70, 0x57, 0x97, 0x88, 0x29, 0x99,
	0xff, 0x82, 0xe8, 0x78, 0x56, 0x76, 0x01, 0xb1, 0x2f, 0xf8, 0x16, 0x8b, 0xcf, 0xce, 0x7a, 0x14,
	0xae, 0xcb, 0x4f, 0xdf, 0x6f, 0x52, 0xe2, 0xfe, 0x35, 0x08, 0xab, 0xdb, 0x2f, 0x9b, 0xf4, 0x64,
	0xec, 0x7f, 0x16, 0x88, 0x29, 0x1d, 0x03, 0x25, 0xe2, 0x06, 0xd3, 0xd3, 0xbb, 0xc0, 0xbf, 0xa3,
	0x8f, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x11, 0xa8, 0x9f, 0xfa, 0x56, 0x02, 0x00, 0x00,
}
